### ISSUE TITLE
[Bug] provide a simple dev-server image

### ISSUE THREAD

**Issue by trajano** [temporalio/docker-builds#270]
### Describe the bug

Make a temporalio/dev-server image.  See Minimal Reproduction for how I work around it.

### Minimal Reproduction

Because of the fact that the admin-tools image is configured to use tini as an entry point thereby preventing the shell from working I had to do this round about way.  The temporal-ui addition was because of#268 which hasn't been marked as resolved yet.

```yaml
  temporal:
    image: temporalio/admin-tools
    #image: temporaliotest/admin-tools
    ports:
      - "7233:7233"
#      - "8233:8233"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7233"]
    entrypoint: [ "temporal", "server", "start-dev", "--ip=0.0.0.0" ]
    environment:
      TEMPORAL_ADDRESS: 0.0.0.0:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
      DB: sqlite
      DB_FILENAME: /tmp/temporal.db
  temporal-ui:
    image: temporaliotest/ui
    ports:
      - "8233:8080"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_HIDE_LOGS: true
      TEMPORAL_CORS_ORIGINS: http://localhost:8233
    depends_on:
      temporal:
        condition: service_healthy
```

### Environment/Versions

- OS and processor:x86 Windows, 
- Are you using Docker 

### Additional context

https://github.com/testcontainers/testcontainers-python/issues/794
